[default]
extend-ignore-re = [
    # Mock token
    ";iuani;ansd;ifgjbnai;sdjfgb",
]

[files]
extend-exclude = [
    # Typo "achived" is a breaking change to fix
    "kotlin/lib/src/main/kotlin/EventType.kt",
    "kotlin/lib/src/main/kotlin/EventTypeListOptions.kt",

    # False positives in randomly-generated strings
    "server/x-server/migrations/20230505222507_operational_webhook_event-types.up.sql",
    "server/x-server/migrations/20230505222507_operational_webhook_event-types.down.sql",
]
