/*
 * Xwebhook API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openweb3.xwebhook.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CustomColorPalette
 */
public class CustomColorPaletteTest {
    private final CustomColorPalette model = new CustomColorPalette();

    /**
     * Model tests for CustomColorPalette
     */
    @Test
    public void testCustomColorPalette() {
        // TODO: test CustomColorPalette
    }

    /**
     * Test the property 'backgroundHover'
     */
    @Test
    public void backgroundHoverTest() {
        // TODO: test backgroundHover
    }

    /**
     * Test the property 'backgroundPrimary'
     */
    @Test
    public void backgroundPrimaryTest() {
        // TODO: test backgroundPrimary
    }

    /**
     * Test the property 'backgroundSecondary'
     */
    @Test
    public void backgroundSecondaryTest() {
        // TODO: test backgroundSecondary
    }

    /**
     * Test the property 'buttonPrimary'
     */
    @Test
    public void buttonPrimaryTest() {
        // TODO: test buttonPrimary
    }

    /**
     * Test the property 'interactiveAccent'
     */
    @Test
    public void interactiveAccentTest() {
        // TODO: test interactiveAccent
    }

    /**
     * Test the property 'navigationAccent'
     */
    @Test
    public void navigationAccentTest() {
        // TODO: test navigationAccent
    }

    /**
     * Test the property 'primary'
     */
    @Test
    public void primaryTest() {
        // TODO: test primary
    }

    /**
     * Test the property 'textDanger'
     */
    @Test
    public void textDangerTest() {
        // TODO: test textDanger
    }

    /**
     * Test the property 'textPrimary'
     */
    @Test
    public void textPrimaryTest() {
        // TODO: test textPrimary
    }

}
