/*
 * Xwebhook API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openweb3.xwebhook.models;

import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Oauth2AuthMethodIn
 */
public class Oauth2AuthMethodInTest {
    /**
     * Model tests for Oauth2AuthMethodIn
     */
    @Test
    public void testOauth2AuthMethodIn() {
        // TODO: test Oauth2AuthMethodIn
    }

}
