/*
 * Xwebhook API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openweb3.xwebhook.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for OneTimeTokenIn
 */
public class OneTimeTokenInTest {
    private final OneTimeTokenIn model = new OneTimeTokenIn();

    /**
     * Model tests for OneTimeTokenIn
     */
    @Test
    public void testOneTimeTokenIn() {
        // TODO: test OneTimeTokenIn
    }

    /**
     * Test the property 'oneTimeToken'
     */
    @Test
    public void oneTimeTokenTest() {
        // TODO: test oneTimeToken
    }

}
