/*
 * Xwebhook API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openweb3.xwebhook.internal.api;

import io.openweb3.xwebhook.internal.ApiException;
import io.openweb3.xwebhook.models.HTTPValidationError;
import io.openweb3.xwebhook.models.HttpErrorOut;
import io.openweb3.xwebhook.models.MessageBroadcastIn;
import io.openweb3.xwebhook.models.MessageBroadcastOut;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BroadcastApi
 */
@Ignore
public class BroadcastApiTest {

    private final BroadcastApi api = new BroadcastApi();

    
    /**
     * Create Broadcast Message
     *
     * Creates a background task to send the same message to each application in your organization
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createBroadcastMessageTest() throws ApiException {
        MessageBroadcastIn messageBroadcastIn = null;
        String idempotencyKey = null;
        MessageBroadcastOut response = api.createBroadcastMessage(messageBroadcastIn, idempotencyKey);

        // TODO: test validations
    }
    
}
