/*
 * Xwebhook API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openweb3.xwebhook.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

/**
 * AppUsageStatsIn
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-07-18T23:47:22.834409+08:00[Asia/Shanghai]")
public class AppUsageStatsIn {
  public static final String SERIALIZED_NAME_APP_IDS = "appIds";
  @SerializedName(SERIALIZED_NAME_APP_IDS)
  private Set<String> appIds = null;

  public static final String SERIALIZED_NAME_SINCE = "since";
  @SerializedName(SERIALIZED_NAME_SINCE)
  private OffsetDateTime since;

  public static final String SERIALIZED_NAME_UNTIL = "until";
  @SerializedName(SERIALIZED_NAME_UNTIL)
  private OffsetDateTime until;


  public AppUsageStatsIn appIds(Set<String> appIds) {
    
    this.appIds = appIds;
    return this;
  }

  public AppUsageStatsIn addAppIdsItem(String appIdsItem) {
    if (this.appIds == null) {
      this.appIds = new LinkedHashSet<>();
    }
    this.appIds.add(appIdsItem);
    return this;
  }

   /**
   * Get appIds
   * @return appIds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Set<String> getAppIds() {
    return appIds;
  }


  public void setAppIds(Set<String> appIds) {
    this.appIds = appIds;
  }


  public AppUsageStatsIn since(OffsetDateTime since) {
    
    this.since = since;
    return this;
  }

   /**
   * Get since
   * @return since
  **/
  @ApiModelProperty(required = true, value = "")

  public OffsetDateTime getSince() {
    return since;
  }


  public void setSince(OffsetDateTime since) {
    this.since = since;
  }


  public AppUsageStatsIn until(OffsetDateTime until) {
    
    this.until = until;
    return this;
  }

   /**
   * Get until
   * @return until
  **/
  @ApiModelProperty(required = true, value = "")

  public OffsetDateTime getUntil() {
    return until;
  }


  public void setUntil(OffsetDateTime until) {
    this.until = until;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AppUsageStatsIn appUsageStatsIn = (AppUsageStatsIn) o;
    return Objects.equals(this.appIds, appUsageStatsIn.appIds) &&
        Objects.equals(this.since, appUsageStatsIn.since) &&
        Objects.equals(this.until, appUsageStatsIn.until);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appIds, since, until);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AppUsageStatsIn {\n");
    sb.append("    appIds: ").append(toIndentedString(appIds)).append("\n");
    sb.append("    since: ").append(toIndentedString(since)).append("\n");
    sb.append("    until: ").append(toIndentedString(until)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

