/*
 * Xwebhook API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openweb3.xwebhook.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.openweb3.xwebhook.models.BorderRadiusEnum;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * BorderRadiusConfig
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-07-25T20:33:19.360168+08:00[Asia/Shanghai]")
public class BorderRadiusConfig {
  public static final String SERIALIZED_NAME_BUTTON = "button";
  @SerializedName(SERIALIZED_NAME_BUTTON)
  private BorderRadiusEnum button;

  public static final String SERIALIZED_NAME_CARD = "card";
  @SerializedName(SERIALIZED_NAME_CARD)
  private BorderRadiusEnum card;

  public static final String SERIALIZED_NAME_INPUT = "input";
  @SerializedName(SERIALIZED_NAME_INPUT)
  private BorderRadiusEnum input;


  public BorderRadiusConfig button(BorderRadiusEnum button) {
    
    this.button = button;
    return this;
  }

   /**
   * Get button
   * @return button
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BorderRadiusEnum getButton() {
    return button;
  }


  public void setButton(BorderRadiusEnum button) {
    this.button = button;
  }


  public BorderRadiusConfig card(BorderRadiusEnum card) {
    
    this.card = card;
    return this;
  }

   /**
   * Get card
   * @return card
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BorderRadiusEnum getCard() {
    return card;
  }


  public void setCard(BorderRadiusEnum card) {
    this.card = card;
  }


  public BorderRadiusConfig input(BorderRadiusEnum input) {
    
    this.input = input;
    return this;
  }

   /**
   * Get input
   * @return input
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BorderRadiusEnum getInput() {
    return input;
  }


  public void setInput(BorderRadiusEnum input) {
    this.input = input;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BorderRadiusConfig borderRadiusConfig = (BorderRadiusConfig) o;
    return Objects.equals(this.button, borderRadiusConfig.button) &&
        Objects.equals(this.card, borderRadiusConfig.card) &&
        Objects.equals(this.input, borderRadiusConfig.input);
  }

  @Override
  public int hashCode() {
    return Objects.hash(button, card, input);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BorderRadiusConfig {\n");
    sb.append("    button: ").append(toIndentedString(button)).append("\n");
    sb.append("    card: ").append(toIndentedString(card)).append("\n");
    sb.append("    input: ").append(toIndentedString(input)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

