/*
 * Xwebhook API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openweb3.xwebhook.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;

/**
 * Sent when an endpoint has been automatically disabled after continuous failures.
 */
@ApiModel(description = "Sent when an endpoint has been automatically disabled after continuous failures.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-08-08T17:18:16.954530+08:00[Asia/Shanghai]")
public class EndpointDisabledEventData {
  public static final String SERIALIZED_NAME_APP_ID = "appId";
  @SerializedName(SERIALIZED_NAME_APP_ID)
  private String appId;

  public static final String SERIALIZED_NAME_APP_UID = "appUid";
  @SerializedName(SERIALIZED_NAME_APP_UID)
  private String appUid;

  public static final String SERIALIZED_NAME_ENDPOINT_ID = "endpointId";
  @SerializedName(SERIALIZED_NAME_ENDPOINT_ID)
  private String endpointId;

  public static final String SERIALIZED_NAME_ENDPOINT_UID = "endpointUid";
  @SerializedName(SERIALIZED_NAME_ENDPOINT_UID)
  private String endpointUid;

  public static final String SERIALIZED_NAME_FAIL_SINCE = "failSince";
  @SerializedName(SERIALIZED_NAME_FAIL_SINCE)
  private OffsetDateTime failSince;


  public EndpointDisabledEventData appId(String appId) {
    
    this.appId = appId;
    return this;
  }

   /**
   * The app&#39;s ID
   * @return appId
  **/
  @ApiModelProperty(example = "app_1srOrx2ZWZBpBUvZwXKQmoEYga2", required = true, value = "The app's ID")

  public String getAppId() {
    return appId;
  }


  public void setAppId(String appId) {
    this.appId = appId;
  }


  public EndpointDisabledEventData appUid(String appUid) {
    
    this.appUid = appUid;
    return this;
  }

   /**
   * The app&#39;s UID
   * @return appUid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "unique-app-identifier", value = "The app's UID")

  public String getAppUid() {
    return appUid;
  }


  public void setAppUid(String appUid) {
    this.appUid = appUid;
  }


  public EndpointDisabledEventData endpointId(String endpointId) {
    
    this.endpointId = endpointId;
    return this;
  }

   /**
   * The ep&#39;s ID
   * @return endpointId
  **/
  @ApiModelProperty(example = "ep_1srOrx2ZWZBpBUvZwXKQmoEYga2", required = true, value = "The ep's ID")

  public String getEndpointId() {
    return endpointId;
  }


  public void setEndpointId(String endpointId) {
    this.endpointId = endpointId;
  }


  public EndpointDisabledEventData endpointUid(String endpointUid) {
    
    this.endpointUid = endpointUid;
    return this;
  }

   /**
   * The ep&#39;s UID
   * @return endpointUid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "unique-ep-identifier", value = "The ep's UID")

  public String getEndpointUid() {
    return endpointUid;
  }


  public void setEndpointUid(String endpointUid) {
    this.endpointUid = endpointUid;
  }


  public EndpointDisabledEventData failSince(OffsetDateTime failSince) {
    
    this.failSince = failSince;
    return this;
  }

   /**
   * Get failSince
   * @return failSince
  **/
  @ApiModelProperty(required = true, value = "")

  public OffsetDateTime getFailSince() {
    return failSince;
  }


  public void setFailSince(OffsetDateTime failSince) {
    this.failSince = failSince;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EndpointDisabledEventData endpointDisabledEventData = (EndpointDisabledEventData) o;
    return Objects.equals(this.appId, endpointDisabledEventData.appId) &&
        Objects.equals(this.appUid, endpointDisabledEventData.appUid) &&
        Objects.equals(this.endpointId, endpointDisabledEventData.endpointId) &&
        Objects.equals(this.endpointUid, endpointDisabledEventData.endpointUid) &&
        Objects.equals(this.failSince, endpointDisabledEventData.failSince);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appId, appUid, endpointId, endpointUid, failSince);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EndpointDisabledEventData {\n");
    sb.append("    appId: ").append(toIndentedString(appId)).append("\n");
    sb.append("    appUid: ").append(toIndentedString(appUid)).append("\n");
    sb.append("    endpointId: ").append(toIndentedString(endpointId)).append("\n");
    sb.append("    endpointUid: ").append(toIndentedString(endpointUid)).append("\n");
    sb.append("    failSince: ").append(toIndentedString(failSince)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

