/*
 * Xwebhook API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openweb3.xwebhook.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * EventTypeExampleOut
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-07-26T22:26:32.587823+08:00[Asia/Shanghai]")
public class EventTypeExampleOut {
  public static final String SERIALIZED_NAME_EXAMPLE = "example";
  @SerializedName(SERIALIZED_NAME_EXAMPLE)
  private Map<String, Object> example = new HashMap<>();


  public EventTypeExampleOut example(Map<String, Object> example) {
    
    this.example = example;
    return this;
  }

  public EventTypeExampleOut putExampleItem(String key, Object exampleItem) {
    this.example.put(key, exampleItem);
    return this;
  }

   /**
   * Get example
   * @return example
  **/
  @ApiModelProperty(example = "{\"data\":{\"email\":\"test@example.com\",\"username\":\"test_user\"},\"type\":\"user.created\"}", required = true, value = "")

  public Map<String, Object> getExample() {
    return example;
  }


  public void setExample(Map<String, Object> example) {
    this.example = example;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EventTypeExampleOut eventTypeExampleOut = (EventTypeExampleOut) o;
    return Objects.equals(this.example, eventTypeExampleOut.example);
  }

  @Override
  public int hashCode() {
    return Objects.hash(example);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EventTypeExampleOut {\n");
    sb.append("    example: ").append(toIndentedString(example)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

