/*
 * Xwebhook API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openweb3.xwebhook.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * InboundPathParams
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-07-18T23:47:22.834409+08:00[Asia/Shanghai]")
public class InboundPathParams {
  public static final String SERIALIZED_NAME_APP_ID = "app_id";
  @SerializedName(SERIALIZED_NAME_APP_ID)
  private String appId;

  public static final String SERIALIZED_NAME_INBOUND_TOKEN = "inbound_token";
  @SerializedName(SERIALIZED_NAME_INBOUND_TOKEN)
  private String inboundToken;


  public InboundPathParams appId(String appId) {
    
    this.appId = appId;
    return this;
  }

   /**
   * The app&#39;s ID or UID
   * @return appId
  **/
  @ApiModelProperty(example = "unique-app-identifier", required = true, value = "The app's ID or UID")

  public String getAppId() {
    return appId;
  }


  public void setAppId(String appId) {
    this.appId = appId;
  }


  public InboundPathParams inboundToken(String inboundToken) {
    
    this.inboundToken = inboundToken;
    return this;
  }

   /**
   * Get inboundToken
   * @return inboundToken
  **/
  @ApiModelProperty(required = true, value = "")

  public String getInboundToken() {
    return inboundToken;
  }


  public void setInboundToken(String inboundToken) {
    this.inboundToken = inboundToken;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InboundPathParams inboundPathParams = (InboundPathParams) o;
    return Objects.equals(this.appId, inboundPathParams.appId) &&
        Objects.equals(this.inboundToken, inboundPathParams.inboundToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appId, inboundToken);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InboundPathParams {\n");
    sb.append("    appId: ").append(toIndentedString(appId)).append("\n");
    sb.append("    inboundToken: ").append(toIndentedString(inboundToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

