/*
 * Xwebhook API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openweb3.xwebhook.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.net.URI;

/**
 * IncomingWebhookPayloadOut
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-08-18T01:36:53.552111+08:00[Asia/Shanghai]")
public class IncomingWebhookPayloadOut {
  public static final String SERIALIZED_NAME_CHANNEL = "channel";
  @SerializedName(SERIALIZED_NAME_CHANNEL)
  private String channel;

  public static final String SERIALIZED_NAME_ERROR = "error";
  @SerializedName(SERIALIZED_NAME_ERROR)
  private String error;

  public static final String SERIALIZED_NAME_INCOMING_WEBHOOK_URL = "incomingWebhookUrl";
  @SerializedName(SERIALIZED_NAME_INCOMING_WEBHOOK_URL)
  private URI incomingWebhookUrl;


  public IncomingWebhookPayloadOut channel(String channel) {
    
    this.channel = channel;
    return this;
  }

   /**
   * Get channel
   * @return channel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getChannel() {
    return channel;
  }


  public void setChannel(String channel) {
    this.channel = channel;
  }


  public IncomingWebhookPayloadOut error(String error) {
    
    this.error = error;
    return this;
  }

   /**
   * Get error
   * @return error
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getError() {
    return error;
  }


  public void setError(String error) {
    this.error = error;
  }


  public IncomingWebhookPayloadOut incomingWebhookUrl(URI incomingWebhookUrl) {
    
    this.incomingWebhookUrl = incomingWebhookUrl;
    return this;
  }

   /**
   * Get incomingWebhookUrl
   * @return incomingWebhookUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public URI getIncomingWebhookUrl() {
    return incomingWebhookUrl;
  }


  public void setIncomingWebhookUrl(URI incomingWebhookUrl) {
    this.incomingWebhookUrl = incomingWebhookUrl;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IncomingWebhookPayloadOut incomingWebhookPayloadOut = (IncomingWebhookPayloadOut) o;
    return Objects.equals(this.channel, incomingWebhookPayloadOut.channel) &&
        Objects.equals(this.error, incomingWebhookPayloadOut.error) &&
        Objects.equals(this.incomingWebhookUrl, incomingWebhookPayloadOut.incomingWebhookUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(channel, error, incomingWebhookUrl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IncomingWebhookPayloadOut {\n");
    sb.append("    channel: ").append(toIndentedString(channel)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    incomingWebhookUrl: ").append(toIndentedString(incomingWebhookUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

