/*
 * Xwebhook API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openweb3.xwebhook.models;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The sending status of the message: - Success &#x3D; 0 - Pending &#x3D; 1 - Fail &#x3D; 2 - Sending &#x3D; 3
 */
@JsonAdapter(MessageStatus.Adapter.class)
public enum MessageStatus {
  
  Success(0),
  
  Pending(1),
  
  Fail(2),
  
  Sending(3);

  private Integer value;

  MessageStatus(Integer value) {
    this.value = value;
  }

  public Integer getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static MessageStatus fromValue(Integer value) {
    for (MessageStatus b : MessageStatus.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<MessageStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final MessageStatus enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public MessageStatus read(final JsonReader jsonReader) throws IOException {
      Integer value = jsonReader.nextInt();
      return MessageStatus.fromValue(value);
    }
  }
}

