version: "3.7"
services:
  rabbitmq:
    image: "docker.io/rabbitmq:3.12-management-alpine"
    ports:
      - "5672:5672"
      - "15672:15672"

  elasticmq: # Drop-in SQS replacement
    image: "docker.io/softwaremill/elasticmq-native:1.5.7"
    ports:
      - "9324:9324"
      - "9325:9325"

  redis:
    image: "docker.io/redis:7-alpine"
    ports:
      - "6379:6379"

  gcp-pubsub:
    image: "gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators"
    ports:
      - "8085:8085"
    command: [
      "gcloud", "beta", "emulators", "pubsub", "start",
      "--project", "local-project",
      "--host-port", "0.0.0.0:8085"
    ]
