name: PHP Release

on:
  push:
    tags:
      - 'v*'

jobs:
  packagist:
    name: Update Packagist
    runs-on: ubuntu-latest

    steps:
      - name: Update Packagist
        run: |
          curl -X POST "https://packagist.org/api/update-package?username=xwebhook&apiToken=$PACKAGIST_API_KEY" \
            -H 'content-type: application/json' \
            -d '{"repository":{"url":"https://packagist.org/packages/xwebhook/xwebhook"}}'
        env:
          PACKAGIST_API_KEY: ${{ secrets.PACKAGIST_API_KEY }}