name: Rust Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Regen openapi libs
        run: |
          yarn
          ./regen_openapi.sh

      - name: Hack around cargo stuff
        run: |
          cd rust/
          git config user.email "work@around.com"
          git config user.name "Work Around"
          git add -f src/apis/ src/models/
          git commit -a -m "Snap"

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "rust -> target"
          # only restore cache for faster publishing, don't save back results
          save-if: false
          # use the cache from rust-lint/stable
          prefix-key: "rust-client-stable"

      - name: Publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish --manifest-path rust/Cargo.toml
