name: Server Security

env:
  CARGO_TERM_COLOR: always

on:
  push:
    branches:
    - main
    paths:
      - 'server/**/Cargo.toml'
      - 'server/**/Cargo.lock'
      - '.github/workflows/server-security.yml'
      - 'deny.toml'
  pull_request:
    paths:
      - 'server/**/Cargo.toml'
      - 'server/**/Cargo.lock'
      - '.github/workflows/server-security.yml'
      - 'deny.toml'

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: EmbarkStudios/cargo-deny-action@v1
        with:
          manifest-path: server/Cargo.toml
